[package]
name = "config_loader"
version = "0.1.0"
edition = "2024"

[dependencies]
config = { version = "0.15", features = ["json", "toml", "yaml"] }
dotenv = "0.15.0"
serde = { version = "1.0.228", features = ["derive"] }
thiserror = "2.0.18"
